server:
  port: 8088

---
spring:
  profiles: default
  cloud:
    gateway: #<<< API Gateway / Routes
      routes:
        - id: auth
          uri: http://localhost:8082
          predicates:
            - Path=/auths/**
          filters:
            - name: JwtAuthenticationFilter
        - id: user
          uri: http://localhost:8083
          predicates:
            - Path=/users/**
          filters:
            - name: JwtAuthenticationFilter
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
          filters:
            - name: JwtAuthenticationFilter
      #>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

---
spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://auth:8080
          predicates:
            - Path=/auths/**
          filters:
            - name: JwtAuthenticationFilter
        - id: user
          uri: http://user:8080
          predicates:
            - Path=/users/**
          filters:
            - name: JwtAuthenticationFilter
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
          filters:
            - name: JwtAuthenticationFilter
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080